site_name: Data Product Observability Metrics Standard
site_url: https://bitol-io.github.io/open-data-product-observability-standard/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: 'home.md'
  - Standard: 'README.md'
  - Examples:
    - 'examples/README.md'
  - Changelog: 'changelog.md'
  - Contributing: 'contributing.md'

extra:
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
